### ISSUE TITLE
`refresh_from_db()` in incompatible with `protected=True` for `django-fsm` fields

### ISSUE THREAD

**Issue by markrofail** [beda-software/drf-writable-nested#124]
The latest version `0.6.2` introduced `refresh_from_db()`
which makes `serializer.update()` fail because of `protected=True` in `django-fsm` fields

The following error occurs
```python
AttributeError: Direct {field_name} modification is not allowed
```

Suggestion:
change `refresh_from_db()` to 
```python
my_obj = MyObject.objects.get(pk=my_obj.pk)
```

**Comment by ir4y** [comment]
Hi @markrofail 
Thank you for your contribution.

`refresh_from_db` is a standard way to update the model.
`django-fsm` uses its own non-standard filed option `protected` to prevent any manual change to FSMField. Basically it overrides `__set__` https://github.com/viewflow/django-fsm/blob/master/django_fsm/__init__.py#L233
Also, it is a known issue https://github.com/viewflow/django-fsm/issues/174

It would be nice if you could contribute to django_fsm and fix the original issue. Usually, it is preferable to fix the source of the bug rather than try to fix bug effects by hacks.

**Comment by markrofail** [comment]
@ir4y Thank you for your prompt reply! My bad, didn't notice the open issue there. WIll try to get it fixed. Thanks!
